### ISSUE TITLE
是否能提供docker版本？

### ISSUE THREAD

**Issue by rakor1986** [ireaderlab/alex#1]
对于一个不懂go语言的小白来说，部署alex太复杂，因为依赖比较多，搞不懂，所以，能不能提供centos或者ubuntu的docker镜像呢？

**Comment by pyloque** [comment]
我后面会补充一下。
不过需要说明的是，压力测试需要良好的网络环境，还会占用大量的cpu资源。
无论容器跑在哪个物理机器上都会导致这台机器的网络和计算性能急剧下降。
alex没有提供很好的资源约束，建议直接跑在物理机器上。
不过既然rakor1986君连docker都玩上了，何不浅学一下go语言呢
